---
title: "Fourth Blog Post"
---


```{r setup, echo = FALSE}
knitr::opts_chunk$set(fig.path = "../images/")
#knitr::opts_chunk$set(fig.path = "C:/Users/Bridget/OneDrive/R_Scripts/repos/brknapp.github.io/images")

```

```{r render, echo = FALSE, eval = FALSE}
rmarkdown::render("C:/Users/Bridget/OneDrive/R_Scripts/repos/brknapp.github.io/_Rmd/2022-07-21-fourth-blog-post.Rmd",
                  output_format = "github_document",
                  output_dir = "C:/Users/Bridget/OneDrive/R_Scripts/repos/brknapp.github.io/_posts/",
                  output_options = list(html_preview=FALSE) 
)
```

```{r 4_32_7_21_2022}
library(tree)
library(readr)
library(tidyverse)
library(class)
library(caret)
library(rpart)
library(rpart.plot)

wine_data<-read.csv("C://Users//Bridget//OneDrive//R_Scripts//repos//brknapp.github.io//wine.data")

colnames(wine_data)<-c("category",
                       "Alcohol",
                       "Malic_acid",
                       "Ash",
                       "Alcalinity_of_ash",
                       "Magnesium",
                       "Total_phenols",
                       "Flavanoids",
                       "Nonflavanoid_phenols",
                       "Proanthocyanins",
                       "Color_intensity",
                       "Hue",
                       "OD280_OD315_of_diluted_wines",
                       "Proline") 
set.seed(dim(wine_data)[1])
train <- sample(1:nrow(wine_data), size = nrow(wine_data)*0.8)
test <- dplyr::setdiff(1:nrow(wine_data), train)
wine_dataTrain <- wine_data[train, ]
wine_dataTest <- wine_data[test, ]
treeFit <- tree(Alcohol ~ ., data = wine_dataTrain)
plot(treeFit); text(treeFit)
cvTree <- cv.tree(treeFit); cvTree
  
  
  
  
  
  
  



```